// This file is generated by rust-protobuf 3.0.3. Do not edit
// .proto file is parsed by protoc --rust-out=...
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `MSAMessage.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_0_3;

#[derive(PartialEq,Clone,Default,Debug)]
// @@protoc_insertion_point(message:proto.MSAMessage)
pub struct MSAMessage {
    // message fields
    // @@protoc_insertion_point(field:proto.MSAMessage.header)
    pub header: ::protobuf::MessageField<super::MSAHeader::MSAHeader>,
    // @@protoc_insertion_point(field:proto.MSAMessage.httpBody)
    pub httpBody: ::std::string::String,
    // special fields
    // @@protoc_insertion_point(special_field:proto.MSAMessage.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a MSAMessage {
    fn default() -> &'a MSAMessage {
        <MSAMessage as ::protobuf::Message>::default_instance()
    }
}

impl MSAMessage {
    pub fn new() -> MSAMessage {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(2);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, super::MSAHeader::MSAHeader>(
            "header",
            |m: &MSAMessage| { &m.header },
            |m: &mut MSAMessage| { &mut m.header },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "httpBody",
            |m: &MSAMessage| { &m.httpBody },
            |m: &mut MSAMessage| { &mut m.httpBody },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<MSAMessage>(
            "MSAMessage",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for MSAMessage {
    const NAME: &'static str = "MSAMessage";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.header)?;
                },
                18 => {
                    self.httpBody = is.read_string()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if let Some(v) = self.header.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        if !self.httpBody.is_empty() {
            my_size += ::protobuf::rt::string_size(2, &self.httpBody);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if let Some(v) = self.header.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(1, v, os)?;
        }
        if !self.httpBody.is_empty() {
            os.write_string(2, &self.httpBody)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> MSAMessage {
        MSAMessage::new()
    }

    fn clear(&mut self) {
        self.header.clear();
        self.httpBody.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static MSAMessage {
        static instance: MSAMessage = MSAMessage {
            header: ::protobuf::MessageField::none(),
            httpBody: ::std::string::String::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for MSAMessage {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("MSAMessage").unwrap()).clone()
    }
}

impl ::std::fmt::Display for MSAMessage {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for MSAMessage {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x10MSAMessage.proto\x12\x05proto\x1a\x0fMSAHeader.proto\"R\n\nMSAMess\
    age\x12(\n\x06header\x18\x01\x20\x01(\x0b2\x10.proto.MSAHeaderR\x06heade\
    r\x12\x1a\n\x08httpBody\x18\x02\x20\x01(\tR\x08httpBodyB\nZ\x08../protoJ\
    \xc2\x01\n\x06\x12\x04\0\0\n\x01\n\x08\n\x01\x0c\x12\x03\0\0\x12\n\x08\n\
    \x01\x02\x12\x03\x01\0\x0e\n\x08\n\x01\x08\x12\x03\x02\0\x1f\n\t\n\x02\
    \x08\x0b\x12\x03\x02\0\x1f\n\t\n\x02\x03\0\x12\x03\x03\0\x19\n\n\n\x02\
    \x04\0\x12\x04\x07\0\n\x01\n\n\n\x03\x04\0\x01\x12\x03\x07\x08\x12\n\x0b\
    \n\x04\x04\0\x02\0\x12\x03\x08\x04\x19\n\x0c\n\x05\x04\0\x02\0\x06\x12\
    \x03\x08\x04\r\n\x0c\n\x05\x04\0\x02\0\x01\x12\x03\x08\x0e\x14\n\x0c\n\
    \x05\x04\0\x02\0\x03\x12\x03\x08\x17\x18\n\x0b\n\x04\x04\0\x02\x01\x12\
    \x03\t\x04\x18\n\x0c\n\x05\x04\0\x02\x01\x05\x12\x03\t\x04\n\n\x0c\n\x05\
    \x04\0\x02\x01\x01\x12\x03\t\x0b\x13\n\x0c\n\x05\x04\0\x02\x01\x03\x12\
    \x03\t\x16\x17b\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(1);
            deps.push(super::MSAHeader::file_descriptor().clone());
            let mut messages = ::std::vec::Vec::with_capacity(1);
            messages.push(MSAMessage::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
